### ISSUE TITLE
Another error when installing plugin

### ISSUE THREAD

**Issue by roel-v** [WMS-Engineering/AusMap#13]
When installing the plugin, I get the error below:

```
TypeError: 'QVariant' object is not subscriptable 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~2.3/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/Roel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\AusMap\__init__.py", line 35, in classFactory
    return AusMap(iface)
  File "C:\Users/Roel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\AusMap\aus_map.py", line 95, in __init__
    locale = QSettings().value('locale/userLocale')[0:2]
TypeError: 'QVariant' object is not subscriptable
```

After this the plugin looks like it is initialized but there is no user interface created for it anywhere.

I looked through the other issue reports but this seems to be a different one.

**Comment by EmHain8** [comment]
I get this as well - it can install but it doesn't load
Couldn't load plugin 'AusMap' due to an error when calling its classFactory() method 

TypeError: 'QVariant' object is not subscriptable 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/Emma/AppData/Roaming/QGIS/QGIS3\profiles\AQ2/python/plugins\AusMap\__init__.py", line 35, in classFactory
    return AusMap(iface)
  File "C:\Users/Emma/AppData/Roaming/QGIS/QGIS3\profiles\AQ2/python/plugins\AusMap\aus_map.py", line 95, in __init__
    locale = QSettings().value('locale/userLocale')[0:2]
TypeError: 'QVariant' object is not subscriptable


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.28.7-Firenze Firenze, fedae0eb52 

Python Path:
C:\Users/Emma/AppData/Roaming/QGIS/QGIS3\profiles\AQ2/python/plugins\qgeo
C:/OSGeo4W/apps/qgis-ltr/./python
C:/Users/Emma/AppData/Roaming/QGIS/QGIS3\profiles\AQ2/python
C:/Users/Emma/AppData/Roaming/QGIS/QGIS3\profiles\AQ2/python/plugins
C:/OSGeo4W/apps/qgis-ltr/./python/plugins
C:\OSGeo4W\apps\grass\grass82\etc\python
C:\OSGeo4W\bin
C:\OSGeo4W\bin\python39.zip
C:\OSGeo4W\apps\Python39\DLLs
C:\OSGeo4W\apps\Python39\lib
C:\OSGeo4W\apps\Python39
C:\OSGeo4W\apps\Python39\lib\site-packages
C:\OSGeo4W\apps\Python39\lib\site-packages\win32
C:\OSGeo4W\apps\Python39\lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Emma/AppData/Roaming/QGIS/QGIS3\profiles\AQ2/python
C:/01_GEOSPATIAL/02_PROJECTS/2023A011 AQ2 Carto/product/deliverable/AQ2_map_template
